version: "3"
services:

  actinia:
    build:
      context: ..
      dockerfile: docker/actinia-core-dev/Dockerfile
    volumes:
      - ./actinia-core-data/grassdb:/actinia_core/grassdb:Z
      - ./actinia-core-data/userdata:/actinia_core/userdata
      - ./actinia-core-data/pgpass:/mnt/pgpass:Z
      - ./actinia-core-data/geodata_dir:/mnt/geodata:Z
      - ./actinia-core-data/workspace/temp_db:/actinia_core/workspace/temp_db
      - ./actinia-core-data/workspace/tmp:/actinia_core/workspace/tmp
      - ./actinia-core-data/resources:/actinia_core/resources
      - ../.:/src/actinia_core/.
      # - ../../actinia-metadata-plugin/:/src/actinia-metadata-plugin/.
      # - ../../actinia-module-plugin/:/src/actinia-module-plugin/.
      # - ../../actinia-stac-plugin/:/src/actinia-stac-plugin/.
      # - ../../actinia-api/:/src/actinia-api/.
    ports:
      - "8088:8088"
    depends_on:
      - redis
      - redis2
    cap_add:
      - SYS_PTRACE
    networks:
    -   actinia-dev

  redis:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
        - "6379:6379"
    networks:
    -   actinia-dev

  redis2:
    image: redis:5.0.4-alpine
    volumes:
      - ./redis_data2:/data
    environment:
      - REDIS_PASS_FILE=/data/config/.redis
    command: [
      "sh", "-c",
      '
      docker-entrypoint.sh
      "/data/config/redis.conf"
      --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    ports:
        - "6377:6379"
    networks:
    -   actinia-dev

networks:
  actinia-dev:
    ipam:
      config:
        - subnet: 172.18.0.0/16
